# Production Docker Compose Configuration
# Use this file for production deployments: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
version: '3.8'

services:
  # Production overrides for Traefik
  traefik:
    environment:
      - TRAEFIK_API_DASHBOARD=false  # Disable dashboard in production
      - TRAEFIK_API_INSECURE=false
    labels:
      # Remove dashboard access in production
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.traefik.middlewares=auth,admin-whitelist"

  # Production overrides for database
  db:
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 1G
    # Enable connection pooling
    command: >
      postgres
      -c max_connections=200
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c work_mem=4MB
      -c min_wal_size=1GB
      -c max_wal_size=4GB
      -c max_worker_processes=8
      -c max_parallel_workers_per_gather=4
      -c max_parallel_workers=8
      -c max_parallel_maintenance_workers=4

  # Production overrides for application
  app:
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.3
      rollback_config:
        parallelism: 1
        delay: 5s
        failure_action: pause
        monitor: 60s
        max_failure_ratio: 0.3
    environment:
      # Production-specific environment variables
      - NODE_ENV=production
      - LOG_LEVEL=warn
      - ENABLE_REQUEST_LOGGING=false
      # Enable production optimizations
      - NODE_OPTIONS=--max-old-space-size=1536
    # Remove development volumes
    volumes: []
    # Remove development ports
    ports: []